### ISSUE TITLE
phpMyAdmin auth

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.info#13]
Our latest changes have just been deployed. Unfortunately, there's still a problem with phpMyAdmin authentication (though not as bad as the previous problem).

Earlier we had the phpMyAdmin URL ending with `phpmyadmin/`, and for some reason, this caused a _"Token Mismatch"_ error, on pretty much any action inside phpMyAdmin.

![token-mismatch](https://cloud.githubusercontent.com/assets/7230211/19161513/63d61fd4-8bf4-11e6-8822-cbbf070e8bd4.png)

Removing the trailing slash seemed to have fixed the problem, but unfortunately introduced another. That is, redirecting to `phpmyadmin/`, which in turn asks the user to authenticate.

![auth](https://cloud.githubusercontent.com/assets/7230211/19161563/97184be2-8bf4-11e6-9f50-09168af44c3f.png)

To make things look worse, Firefox displays a warning about potential tricking

![warning](https://cloud.githubusercontent.com/assets/7230211/19162064/9b5ff1a8-8bf6-11e6-9212-7f734b09773d.png)

Once the user puts in her username and password (outputted by `username50` and `password50`, respectively), all looks good (i.e., no token mismatch error or anything), and credentials are even remembered, but that's not the point.

---

Alternatively we could:
1. Open `phpmyadmin/` and have the user manually authenticate and the browser remember.
2. Use another phpMyAdmin authentication mode, particularly [Signon](http://docs.phpmyadmin.net/en/latest/setup.html#signon-authentication-mode) might be of interest? 
   
   The idea is to tweak a couple of phpMyAdmin configs in `/etc/phpmyadmin/config.inc.php` and add a PHP script through our ide50.deb:
   1. set [`$cfg['Servers'][$i]['auth_type']`](http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_auth_type) to `'signon'`.
   2. set [`$cfg['Servers'][$i]['SignonScript']`](http://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_SignonScript) to the path of the PHP script that will read `MYSQ_USERNAME` and `MYSQL_PASSWORD` and return them.

Thoughts, @dmalan and @glennholloway?

**Comment by dmalan** [comment]
Hey, sorry for missing this so long ago. Did you close because we redressed?

**Comment by kzidane** [comment]
Oh, not really. Just because it's been quite long and we've moved away from phpmyadmin. Also Firefox doesn't warn anymore (at least on Ubuntu); they might have fixed that in a recent version, so this shouldn't be an issue for the user meanwhile.

However, figured there's another authentication mode called 'config', which works by simply placing credentials in `/etc/phpmyadmin/config.inc.php`. I'll PR ide50.deb shortly to use this authentication mode instead!

**Comment by dmalan** [comment]
So we've avoided `config` mode, since if a student makes their app public, then their database is publicly accessible and writeable. Better to keep the credentials in our menu option's URL. 

CS50 AP will still be using phpMyAdmin, though, through June. Is it indeed still functional then?

**Comment by kzidane** [comment]
> Better to keep the credentials in our menu option's URL.

Hm, alright, I'll see if the token mismatch problem is fixed in a recent phpmyadmin release, and let you know. If it's not, though, we should probably stick to asking about username and password?

> Is it indeed still functional then?

Yes. Just asks for a username and a password, and the browser caches them.

**Comment by dmalan** [comment]
Perhaps on point?

http://stackoverflow.com/questions/18076499/phpmyadmin-token-mismatch-for-long-time-idle

Specifically, "Ubuntu has a cleanup script in /etc/cron.d/php5 which
deletes files in /var/lib/php5: changing session.save_path bypass that
cleanup script"?

**Comment by kzidane** [comment]
Apologies for the belated reply! Nope, afraid this doesn't fix it! I'm quite sure this is a bug in this version. Though, should probably see if it exists in newer versions, and upgrade, if not.

**Comment by dmalan** [comment]
Hm, are sessions being stored elsewhere? There aren't many other factors that would explain why sessions eventually die.
