### ISSUE TITLE
update notification

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.info#18]
@dmalan and @glennholloway, how do you find this? Should help minimize the number of questions about problems whose fix is simply running `update50`.

Also, if we're to implement this, what do you think would be the best way to check for a newer version? `apt-get update && apt-cache policy` or simply reorganize our cs50/ide50, so that the version is in a separate file, and simply read from that? And how frequently should we check? Daily?

![update-dark](https://cloud.githubusercontent.com/assets/7230211/22863713/2a40c9da-f14e-11e6-8f94-9cecb70b8585.png)

![update-light](https://cloud.githubusercontent.com/assets/7230211/22863714/2a4c18c6-f14e-11e6-9b14-2bcc21388354.png)

**Comment by dmalan** [comment]
I like the idea. Though we should perhaps make it even more obvious, as by blinking the identifier? Or does Cloud9's SDK also allow you to display a banner message along the top of the viewport?

Not opposed to having, e.g., a VERSION file in GitHub, but what's more important is what's available on the mirror, but a new VERSION could appear on GitHub before it's propagated to the mirror as a deb. So an out-of-band way to check what version is available is to query our mirror.cs50.net AWS Cloudfront distribution via the Amazon S3 JavaScript API. E.g., see the JavaScript source of view-source:http://mirror.cs50.net/ide50/2015/dists/trusty/main/binary-amd64/ for how we do it to generate directory indexes. However, using `apt-cache` and such is probably the "right" way, if not too expensive to trigger from a plugin daily? Or perhaps anytime the IDE is opened?

**Comment by kzidane** [comment]
> Or does Cloud9's SDK also allow you to display a banner message along the top of the viewport?

Oh, I thought you didn't like the notification bar? Personally, I find the icon simpler, but definitely can do notification, if you prefer.

![](https://files.readme.io/SnOqgbBTnSmGAnDSsb9w_2015-02-13_2134.png) 

https://cloud9-sdk.readme.io/docs/using-dialogs#section-dialog-notification

> using apt-cache and such is probably the "right" way, if not too expensive to trigger from a plugin daily? Or perhaps anytime the IDE is opened?

I think so too. Gonna go with that then!

**Comment by dmalan** [comment]
We can start with the icon approach if you'd like!
